MKLPATH = /software/intel/lib/intel64
MKLINCLUDE = /software/intel/include
GSLPATH = $(GSL_DIR)/lib
GSLINC = $(GSL_DIR)/include
GMXPATH = /project/gavoth/jwwagner/local/lib
GMXINC = /project/gavoth/jwwagner/local/include
LIBINC = /usr/include
WARN_FLAGS = -Wall -Wextra -wn=3 -Wwrite-strings -Wuninitialized -Wstrict-prototypes -Wreorder -Wreturn-type
OPT = -O2 -std=c++11 $(WARN_FLAGS)
MKL_OPT = -O2 -lmkl_gf_lp64 -lmkl_intel_thread -lmkl_core -fopenmp -std=c++11 $(WARN_FLAGS)

LIBS         = $(GSLPATH)/libgsl.a -mkl -lm -lxdrfile -L$(LIBINC)
LDFLAGS      = $(OPT) -L$(GMXPATH) -L$(GSLPATH)
CFLAGS	     = $(OPT) -I$(GSLINC) -I$(GMXINC) -I$(GMXINC)/xdrfile
MKL_LDFLAGS  = $(MKL_OPT) -L$(GMXPATH) -L$(GSLPATH)
MKL_CFLAGS   = $(MKL_OPT) -I$(GSLINC) -I$(GMXINC) -I$(GMXINC)/xdrfile
NO_GRO_LIBS    = $(GSLPATH)/libgsl.a -mkl -lm -L$(LIBINC)
NO_GRO_LDFLAGS = $(OPT) -L$(GSLPATH)
NO_GRO_CFLAGS  = $(OPT) -I$(GSLINC)
MKL_NO_GRO_LIBS    = $(GSLPATH)/libgsl.a -mkl -lm -L$(LIBINC)
MKL_NO_GRO_LDFLAGS  = $(MKL_OPT) -L$(GSLPATH)
MKL_NO_GRO_CFLAGS   = $(MKL_OPT) -I$(GSLINC)

CC           = icc

COMMON_OBJECTS = control_input.o fm_output.o force_computation.o geometry.o interaction_hashing.o interaction_model.o matrix.o splines.o topology.o trajectory_input.o misc.o
COMMON_SOURCE = control_input.h fm_output.h force_computation.h geometry.h interaction_hashing.h interaction_model.h matrix.h splines.h topology.h trajectory_input.h misc.h
MKL_COMMON_OBJECTS = control_input.o fm_output.o force_computation.o geometry.o interaction_hashing.o interaction_model.o matrix_mkl.o splines.o topology.o trajectory_input.o misc.o
NO_GRO_COMMON_OBJECTS = control_input.o fm_output.o force_computation.o geometry.o interaction_hashing.o interaction_model.o matrix.o splines.o topology.o trajectory_input_no_gro.o misc.o
MKL_NO_GRO_COMMON_OBJECTS = control_input.o fm_output.o force_computation.o geometry.o interaction_hashing.o interaction_model.o matrix_mkl.o splines.o topology.o trajectory_input_no_gro.o misc.o

# Target executables

# The library for LAMMPS is lib_mscg.a
lib_mscg.a: mscg.o $(NO_GRO_COMMON_OBJECTS) range_finding.o
	ar rvs lib_mscg.a *.o

newfm.x: newfm.o $(COMMON_OBJECTS)
	$(CC) $(LDFLAGS) -o $@ newfm.o $(COMMON_OBJECTS) $(LIBS)

newfm_mkl.x: newfm.o $(MKL_COMMON_OBJECTS)
	$(CC) $(MKL_LDFLAGS) -o $@ newfm.o $(MKL_COMMON_OBJECTS) $(LIBS) -D"_mkl_flag=1"

newfm_no_gro.x: newfm.o $(NO_GRO_COMMON_OBJECTS)
	$(CC) $(NO_GRO_LDFLAGS) -o $@ newfm.o $(NO_GRO_COMMON_OBJECTS) $(NO_GRO_LIBS) -D"_exclude_gromacs=1"

newfm_mkl_no_gro.x: newfm.o $(MKL_NO_GRO_COMMON_OBJECTS)
	$(CC) $(MKL_NO_GRO_LDFLAGS) -o $@ newfm.o $(MKL_NO_GRO_COMMON_OBJECTS) $(MKL_NO_GRO_LIBS) -D"_exclude_gromacs=1" -D"_mkl_flag=1"

rangefinder.x: rangefinder.o range_finding.o $(COMMON_OBJECTS)
	$(CC) $(LDFLAGS) -o $@ rangefinder.o range_finding.o $(COMMON_OBJECTS) $(LIBS)

rangefinder_no_gro.x: rangefinder.o range_finding.o $(NO_GRO_COMMON_OBJECTS)
	$(CC) $(NO_GRO_LDFLAGS) -o $@ rangefinder.o range_finding.o $(NO_GRO_COMMON_OBJECTS) $(NO_GRO_LIBS) -D"_exclude_gromacs=1"

# Target objects

mscg.o: mscg.cpp $(COMMON_SOURCE) range_finding.o
	$(CC) $(CFLAGS) -c mscg.cpp -o mscg.o

newfm.o: newfm.cpp $(COMMON_SOURCE)
	$(CC) $(CFLAGS) -c newfm.cpp
	
newfm_mkl.o: newfm.cpp $(COMMON_SOURCE) 
	$(CC) $(MKL_CFLAGS) -c newfm.cpp -D"_mkl_flag=1" -o newfm_mkl.o

rangefinder.o: rangefinder.cpp range_finding.h $(COMMON_SOURCE)
	$(CC) $(CFLAGS) -c rangefinder.cpp

scalarfm.o: scalarfm.cpp $(COMMON_SOURCE)
	$(CC) $(CFLAGS) -c scalarfm.cpp

batch_fm_combination.o: batch_fm_combination.cpp batch_fm_combination.h external_matrix_routines.h misc.h
	$(CC) $(CFLAGS) -c batch_fm_combination.cpp

batch_fm_combination_mkl.o: batch_fm_combination.cpp batch_fm_combination.h external_matrix_routines.h misc.h
	$(CC) $(MKL_CFLAGS) -c batch_fm_combination.cpp -D"_mkl_flag=1" -o batch_fm_combination_mkl.o

control_input.o: control_input.cpp control_input.h misc.h
	$(CC) $(CFLAGS) -c control_input.cpp

geometry.o: geometry.h
	$(CC) $(CFLAGS) -c geometry.cpp

fm_output.o: fm_output.cpp fm_output.h force_computation.h misc.h
	$(CC) $(CFLAGS) -c fm_output.cpp

force_computation.o: force_computation.cpp force_computation.h interaction_model.h matrix.h trajectory_input.h misc.h
	$(CC) $(CFLAGS) -c force_computation.cpp

interaction_hashing.o: interaction_hashing.cpp interaction_hashing.h
	$(CC) $(CFLAGS) -c interaction_hashing.cpp

interaction_model.o: interaction_model.cpp interaction_model.h control_input.h interaction_hashing.h topology.h misc.h
	$(CC) $(CFLAGS) -c interaction_model.cpp

matrix.o: matrix.cpp matrix.h control_input.h external_matrix_routines.h interaction_model.h misc.h
	$(CC) $(CFLAGS) -c matrix.cpp

matrix_mkl.o: matrix.cpp matrix.h control_input.h external_matrix_routines.h interaction_model.h misc.h
	$(CC) $(MKL_CFLAGS) -c matrix.cpp -D"_mkl_flag=1" -o matrix_mkl.o

misc.o: misc.cpp misc.h
	$(CC) $(CFLAGS) -c misc.cpp

range_finding.o: range_finding.cpp range_finding.h force_computation.h interaction_model.h matrix.h misc.h
	$(CC) $(CFLAGS) -c range_finding.cpp

splines.o: splines.h interaction_model.h
	$(CC) $(CFLAGS) -c splines.cpp

topology.o: topology.cpp topology.h interaction_model.h misc.h
	$(CC) $(CFLAGS) -c topology.cpp

trajectory_input.o: trajectory_input.cpp trajectory_input.h control_input.h misc.h
	$(CC) $(CFLAGS) -c trajectory_input.cpp

trajectory_input_no_gro.o: trajectory_input.cpp trajectory_input.h control_input.h misc.h
	$(CC) $(NO_GRO_CFLAGS) -c trajectory_input.cpp -D"_exclude_gromacs=1" -o trajectory_input_no_gro.o

# Other convenient commands
clean:
	rm *.[o]

all:
	make newfm.x; \
	make rangefinder.x;
